Updated pipeline

diff --git a/.github/workflows/iac-deployment.yaml b/.github/workflows/iac-deployment.yaml
--- a/.github/workflows/iac-deployment.yaml
+++ b/.github/workflows/iac-deployment.yaml
@@ -60,14 +60,26 @@ jobs:
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.5.0
-          terraform_wrapper: false 
+          terraform_wrapper: true 
 
       - name: Terraform Init
         run: terraform init -upgrade
 
       - name: Terraform Plan
         id: plan
-        run: terraform plan -lock=false -out=tfplan.binary
+        run: |
+          set +e 
+          terraform plan -lock=false -out=tfplan.binary
+          TF_EXIT_CODE=$?
+          set -e
+          
+          if [ -f "tfplan.binary" ]; then
+            echo "Plan file successfully generated."
+            exit 0
+          else
+            echo "Plan failed to generate."
+            exit $TF_EXIT_CODE
+          fi
         
       - name: Compress Plan
         run: tar -czvf tfplan.tar.gz tfplan.binary
@@ -115,7 +127,7 @@ jobs:
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: 1.5.0
-          terraform_wrapper: false 
+          terraform_wrapper: true 
 
       - name: Terraform Init
         run: terraform init
